services:
  Effiana\CronBundle\Services\CommandParser:
    public: true
    arguments:
    - "@kernel"

  Effiana\CronBundle\Form\Type\CommandChoiceType:
    public: true
    autowire: true
    tags:
    - { name: form.type, alias: command_choice }

  Effiana\CronBundle\Command\:
    autowire: true
    autoconfigure: true
    resource: '../../Command'
    tags: [console.command]

  Effiana\CronBundle\Cron\Resolver:
    autowire: true
    public: true
    arguments:
    - "@Effiana\\CronBundle\\Cron\\Manager"
    - "@Effiana\\CronBundle\\Cron\\CommandBuilder"
    - "%kernel.root_dir%"
  Effiana\CronBundle\Cron\Manager:
    autowire: true
    arguments: ["@doctrine"]
    public: true
  Effiana\Cron\Executor\Executor:
    autowire: true
    public: true
  Effiana\CronBundle\Cron\CommandBuilder:
    autowire: true
    public: true
    arguments: ["%kernel.environment%"]

  Effiana\Cron\Validator\CrontabValidator:
    public: true