parameters:
  cron.resolver.class:        Effiana\CronBundle\Cron\Resolver
  cron.manager.class:         Effiana\CronBundle\Cron\Manager
  cron.command_builder.class: Effiana\CronBundle\Cron\CommandBuilder
  cron.executor.class:        Effiana\Cron\Executor\Executor
  cron.validator.class:       Effiana\Cron\Validator\CrontabValidator

services:
  Effiana\CronBundle\Services\CommandParser:
    public: true
    arguments:
    - "@kernel"

  Effiana\CronBundle\Form\Type\CommandChoiceType:
    public: true
    autowire: true
    tags:
    - { name: form.type, alias: command_choice }

  Effiana\CronBundle\Command\:
    resource: '../../Command'
    tags: [console.command]

  cron.resolver:
    class: "%cron.resolver.class%"
    arguments: ["@cron.manager", "@cron.command_builder", "%kernel.root_dir%"]
    public: true
  cron.manager:
    class: "%cron.manager.class%"
    arguments: ["@doctrine"]
    public: true
  cron.executor:
    class: "%cron.executor.class%"
    public: true
  cron.command_builder:
    class: "%cron.command_builder.class%"
    arguments: ["%kernel.environment%"]
  cron.validator:
    public: true
    class: "%cron.validator.class%"
